D2_app/urls.py
from django.urls import path
from .views import Ledger
from .views import MainView,LoginView,SignUpView,RegisterView,DocumentView,ApprovalView
from .views import LedgerList

app_name='D2_app'
urlpatterns = [
    path('main/',MainView.as_view(),name='main'),
    path('list/',Ledger.as_view(),name='list'),
    path('login',LoginView.as_view(),name='login'),
    path('signup',SignUpView.as_view(),name='signup'),
    path('register',RegisterView.as_view(),name='register'),
    path('ledger_list',LedgerList.as_view(),name='ledger_list'),
    path('approval',ApprovalView.as_view(),name='approval'),
    path('document',DocumentView.as_view(),name='document'),
]

ledger/urls.py
from django.contrib import admin
from django.urls import path, include
import D2_app.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('D2_app/',include('D2_app.urls'),name='D2_app')
]

templates/base.html
{% load static%}
<!doctype html>
<html lang="ja">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}Ledger web-system{% endblock %}</title>

	<link rel="stylesheet"href="{% static '/css/base.css'%}">
	{% block css %}{% endblock %}
</head>
<body>
	<header>
            <table class="header-table">
                <tr>
                    <th colspan="3">
                        <div class="upper_space"></div>
                    </th>
                </tr>
                <td>
                    <a href="{% url 'D2_app:main' %}" alt="メインへ戻る">
                        <img src="{% static "/images/common/LEDGER.png"%}" width="90%" alt="ロゴの名前"> 
                    </a> 
                </td>
                <td>
                    <p class="title">{% block page_name %}メイン画面{% endblock%}</p>
                </td>
                <td>
                    <button class="logout-botton" onclick=location.href="{% url 'D2_app:login' %}">
                        ログアウト
                    </button>
                </td>
            </table>                    
	</header>
	<div class="container">
	</div>
	{% block main %}{% endblock %}
	<footer>
		<table class="buttons">
			<tbody>
				<tr>
					<td colspan="6">
						<div class="under_space"></div>
					</td>
				</tr>
				<tr>
					<td></td>
					<td></td>
					<td class="string">困ったときは</td>
					<td class="string">メインメニュー</td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td></td>
					<td></td>
					<td><button class="information-botton" onclick=location.href="{% url 'D2_app:document' %}">
						<img src="{%static "/images/common/info.png"%}" height="45" margin="2px" alt="ロゴの名前"></button>
					</td>
					<td><button class="home-botton" onclick=location.href="{% url 'D2_app:main' %}">
						<img src="{%static "/images/common/home.png"%}" height="45" margin: 5px alt="ロゴの名前"></button>
					</td>
					<td></td>
					<td></td>
				</tr>
			</tbody>   
			
		</table>
	</footer>
</body>
</html>