D2_app/urls.py
from django.urls import path
from .views import Ledger
from .views import MainView,LoginView,SignUpView,RegisterView,DocumentView,ApprovalView
from .views import LedgerList

app_name='D2_app'
urlpatterns = [
    path('main/',MainView.as_view(),name='main'),
    path('list/',Ledger.as_view(),name='list'),
    path('login',LoginView.as_view(),name='login'),
    path('signup',SignUpView.as_view(),name='signup'),
    path('register',RegisterView.as_view(),name='register'),
    path('ledger_list',LedgerList.as_view(),name='ledger_list'),
    path('approval',ApprovalView.as_view(),name='approval'),
    path('document',DocumentView.as_view(),name='document'),
]

ledger/urls.py
from django.contrib import admin
from django.urls import path, include
import D2_app.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('D2_app/',include('D2_app.urls'),name='D2_app')
]

shoppinglist/urls.py
from django.urls import path
from .views import ItemList, ItemEditView,ItemShowView,ItemDeleteView,ItemAddView
from .views import ItemMainView,LoginView,SignUpView,RegisterView,DocumentView,ApprovalView
from .views import LedgerList

app_name = 'shoppinglist'
urlpatterns = [
    path('list/',LedgerList.as_view(),name='list'),
#     path('list/',ItemList.as_view(),name='list'),
    path('add', ItemAddView.as_view(), name='add'),
    
    path('edit/<int:pk>', ItemEditView.as_view(),name='edit'),

    path('show', ItemShowView.as_view(), name='show'),
    path('delete<int:pk>', ItemDeleteView.as_view(), name='delete'),
    path('main',ItemMainView.as_view(),name='main'),
    path('login',LoginView.as_view(),name='login'),
    path('signup',SignUpView.as_view(),name='signup'),
    path('register',RegisterView.as_view(),name='register'),
    path('ledger_list',LedgerList.as_view(),name='ledger_list'),
    path('approval/<int:pk>',ApprovalView.as_view(),name='approval'),
    path('document',DocumentView.as_view(),name='document'),
    ]

D2_app/models.py
from django.db import models


#各属性の制約は未実装
#間に合わせでかなり雑に定義しています
class User(models.Model):
    username = models.CharField(max_length=100)
    userID = models.CharField(max_length=100, primary_key=True)
    password = models.CharField(max_length=100)
    class Meta:
        db_table = 'ユーザ表'  #テーブル名："ユーザ表"
        
    def __str__(self):
        return self.userID
    
#verbose_nameで項目の名前を指定できる
#日付の入力形式は未実装
class Ledger(models.Model):
    fileID = models.BigIntegerField(primary_key=True)
    userID = models.ForeignKey(User, blank=True, null=True, verbose_name='user', on_delete=models.PROTECT)
    attachedField = models.CharField('属性', max_length=100)   #5パターンのいずれかに変更すべし
    
    IS_USED_CHOICES = (
        (False, '請求書'),
        (True, '領収書'),
    )
    #請求書、領収書の種別
    category = models.BooleanField('種別', choices=IS_USED_CHOICES, help_text='請求書ならfalse')
    
    input_date = models.DateField('日付', blank=True,null=True)
    client = models.CharField('相手先', max_length=100)#全角文字指定に変更すべし
    consumptionTax_rate = models.PositiveIntegerField('消費税率', default=10)
    consumptionTax = models.PositiveIntegerField('消費税', default=0)
    excludingTax = models.PositiveIntegerField('税抜金額', default=0)
    includingTax = models.PositiveIntegerField('税込金額', default=0)
#     note = models.TextField('備考', blank=True, null=True, max_length=1000, verbose_name='備考')
    registration_date = models.DateField('登録日時', blank=True,null=True)
    approval_date = models.DateField('承認日時', blank=True,null=True)
    image_url = models.URLField('画像url', blank=True, null=True)
    
    
    class Meta:
        db_table = '帳簿表'
    
#     def __str__(self):
#         return self.fileID

class RelatedDocument(models.Model):
    relatedFileID = models.BigIntegerField( primary_key=True)
    userID = models.ForeignKey(User, blank=True, null=True, verbose_name='user', on_delete=models.PROTECT)
    image_url = models.URLField('画像url', blank=True, null=True)
    
    class Meta:
        db_table = '関係書類表'  #テーブル名："ユーザ表"
        
#     def __str__(self):
#         return self.relatedFileID

D2_app/views.py
# Create your views here.
from .models import Ledger
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404
# from .forms import ItemBuy, ItemIdForm, ItemForm
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from multiprocessing.sharedctypes import template
from django.contrib.gis.db.backends.spatialite import client
from django.urls.base import reverse_lazy
from django.views.generic.list import ListView


class Ledger(ListView):
    model = Ledger
    template_name='D2_app/list.html'

class MainView(TemplateView):
    template_name = 'D2_app/main.html'
    success_url = reverse_lazy('list')
     
class LoginView(TemplateView):
    template_name ='D2_app/login.html'
 
class SignUpView(TemplateView):
    template_name ='D2_app/signup.html'
     
class RegisterView(CreateView):
    model = Ledger
    fields = ('category','input_date','client','consumptionTax','excludingTax','includingTax')
    template_name = 'D2_app/register.html'
    success_url = 'list/'    
 
class ApprovalView(UpdateView):
    model = Ledger
    fields = ('category','input_date','client','consumptionTax_rate','consumptionTax','excludingTax','includingTax')
# #     context['category'] = CategoryForm()
    template_name = 'D2_app/approval.html'
    success_url = reverse_lazy('ledger_list')
# #     success_url = 'list/'    
class LedgerList(ListView):
    model = Ledger
    template_name = 'D2_app/ledger.html'
     
class DocumentView(TemplateView):
    template_name ='D2_app/document.html'

D2_app/templates/D2_app/approval.html
{% extends "base.html" %}
{% load static %}

{% block title %} Aproval {% endblock %}
{% block page_name %}承認操作{% endblock %}
{% block main %}
<link href="{% static '/css/approval.css'%}" rel="stylesheet">
<form action = "{% url 'D2_app:approval' %}", method="post">
{% csrf_token %}
{{ form }}
<input type="submit" value = "更新">
</form>
<div id="tbl-bdr">
    <table class="form">
        <tr>
            <td class="type">
            種別
            </td>
            <td colspan="2">{{form.category}}</td>
        </tr>
        
        <tr>
            <td class="type">日付</td>
            <td  colspan="2">{{form.input_date}}</td>
        </tr>
        
        <tr>
            <td class="type">相手先</td>
            <td colspan="2">{{form.client}}</td>
        </tr>
        
        <tr>
            <td rowspan="4" class="type">金額</td>
            <td class="money_type">税率</td>
            <td>{{form.consumptionTax_rate}}</td>
        </tr>

        <tr>
            <td class="money_type">消費税</td>
            <td>{{form.consumptionTax}}</td>
        </tr>

        <tr>
            <td class="money_type">税抜き</td>
            <td>{{form.excludingTax}}</td>
        </tr>

        <tr>
            <td class="money_type">総額</td>
            <td class="A">{{form.includingTax}}</td>
        </tr>

        <tr>
            <td class="type">備考</td>
            <td colspan="2">ECT</td>
        </tr>
        </table>
</div>

<table>
    {{ form.as_table }}
    <tr>
        <td class = "name">
            種類
        </td>
        <td>  
            {{ form.category }}
        </td>
    </tr>
    <tr>
        <td class="name">
            
    </tr>
</table>
<input type="submit"/>
</form>
{% endblock %}

D2_app/templates/D2_app/document.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="ja">
        <title>Ledger web-system</title>
        <meta name="description" content="ページの概要文を掲載します">
        <meta name="viewport" content="device-width">
        <link href="{% static '/css/document.css'%}" rel="stylesheet">
    </head>
    <body>
        <header class="header">
            <a href="./common.html" alt="メインへ戻る">
                <img src="./images/common/LEDGER.png" width="50%" alt="ロゴの名前"> 
            </a>                       
            <h1 class="title">説明書類</h1>
        </header>
            <div class="header-inner">
            </div>
        <main class="main">

            <h2 class="check">まずは書類をご確認ください。</h2>
            <div class="information">
                <div class="documents">
                    <ul class="name">
                        <li>
                            <a href="https://www.google.co.jp/?hl=ja"rel="noopener noreferrer">システム概要書</a>
                        </li>
                        <li>システム仕様書</li>
                        <li>操作マニュアル</li>
                      </ul>
                </div>
                <img src="./images/document/information.png" width="50%" alt="マーク">
                
            </div>

            
        </main>

        <footer class="footer">
            <div class="upper">
                <div class="upper-str-right"><h2>メインメニュー</h2></div>
            </div>

            <button class="home-botton" onclick="location.href='./common.html'">
                <div class="home">
                    <img src="./images/common/home.png" height="45" margin: 5px alt="ロゴの名前">
                </div>
        </footer>
    </body>
</html>

D2_app/templates/D2_app/file_list.html
{% extends "base.html" %}

{% block title %} 個別リスト{% endblock%}

{% block main %}
<div class="func">
	<form action="{% url 'D2_app:list' %}" method="post">
		{% csrf_token %}
		{{ form }}
		<input type="submit"/>
		</form>	
</div>


<table class="table">
	<thead class="table-dark">
		<tr>
			<th>ID</th>
			<th>名前</th>
			<th>個数</th>
			<th>期日</th>
			<th>済み?</th>
			<!-- <th>表示</th> -->
			<th>編集</th>
			<th>削除</th>
			</tr>
		</thead>
		
<tbody>
{% for item in object_list%}
	<tr>
		<td scope="row">{{ item.id }}</td>
		<td >{{ item.name }}</td>
		<td>{{ item.count}}</td>
		<td>{{ item.buy_date}}</td>
		<td>{% if item.buy == False %} <font color='red'>Not Yet</font> {% endif %}{% if item.buy == True %} Yet {% endif %}</td>
		<!-- <td><a href="{% url 'D2_app:show' %}">表示</a></td> -->
		<td><a href="{% url 'D2_app:edit' item.id %}">編集</a></td>
		<td><a href="{% url 'D2_app:delete' item.id %}">削除</a></td>
		
	</tr>
{% endfor%}
</tbody>
</table>
<ul>
	<!-- <li><a href="{% url 'D2_app:add' %}">追加</a></li>
	<li><a href="{% url 'D2_app:show' %}">表示</a></li> -->
	<li><a href="{% url 'D2_app:main' %}">main</a></li>
	
	<form method="post" enctype="multipart/form-data">		
		<input type="file">
		<button type="submit">submit</button>	
	</form>

</ul>

{% endblock%}

D2_app/templates/D2_app/item_show.html
{% extends "base.html" %}

{% block title %} 個別リスト {% endblock %}

{% block main %}
</form>

{% if item %}
<dl>
<dt>名前</dt><dd>{{ item.name }}</dd>
<dt>個数</dt><dd>{{ item.count }}</dd>
<dt>期日</dt><dd>{{ item.buy_date }}</dd>
<dt>済み？</dt><dd>{{ item.buy }}</dd>
<dt>店</dt><dd>{{ item.shop }}</dd>
</dl>
{% endif %}
<ul>
<li><a href="{% url 'D2_app:register' %}"><input type="button" value="アップロード"></a></li>
<li><a href="{% url 'D2_app:main' %}"><input type="button" value="キャンセル"></a></li>
</ul>
{% endblock %}

D2_app/templates/D2_app/ledger_list.html
{% extends "base.html" %}
{% load static %}

{% block title %} LEDGER {% endblock %}
{% block page_name %}承認操作{% endblock %}

{% block main %}
<link href="{% static '/css/ledger_list.css'%}" rel="stylesheet">
<!-- <div class="func">
	<form action="{% url 'D2_app:list' %}" method="post">
		{% csrf_token %}
		{{ form }}
		<input type="submit"/>
		</form>	
</div> -->
<div class="span"></div>
<div id="tbl-bdr">
	<table class="table">
		<thead class="table-dark">
			<tr>
				<!-- <th class="adjust"></th> -->
				<th>ID</th>
				<th>状態</th>
				<th>種類</th>
				<th>日付</th>
				<th>相手先</th>
				<th>金額</th>
				<th>登録日</th>
				<!-- <th>表示</th> -->
				<th></th>
				<!-- <th></th> -->
				</tr>
			</thead>
			
	<tbody class="body">
	{% for ledger in object_list %}
		<tr>
			<td>{{ ledger.pk }}</td>
			<td>{{ ledger.attachedField }}</td>
			<td>{% if ledger.category == False %} 請求書 {% endif %}{% if ledger.category == True %} 領収書 {% endif %}</td>
			<td>{{ ledger.input_date }}</td>
			<td>{{ ledger.client }}</td>
			<td>{{ ledger.includingTax }}円</td>
			<td>{{ ledger.registration_date }}</td>
			<td>
				<button class="detail" onclick=location.href="{% url 'D2_app:approval' ledger.pk%}">
					<!-- <img src="{%static "/images/common/info.png"%}" height="45" margin="2px" alt="ロゴの名前"></button> -->
				詳細を表示</td>
		</tr>
	{% endfor%}
	</tbody>
	</table>
</div>


<ul>
	<!-- <li><a href="{% url 'D2_app:add' %}">追加</a></li>
	<li><a href="{% url 'D2_app:show' %}">表示</a></li> -->
	<!-- <li><a href="{% url 'D2_app:main' %}">main</a></li> -->
	


</ul>

{% endblock%}

D2_app/templates/D2_app/list.html
{% extends "base.html" %}
{% load static %}

{% block title %} LEDGER {% endblock %}
{% block page_name %}承認操作{% endblock %}

{% block main %}

<div class="span"></div>
<div id="tbl-bdr">
	<table class="table">
		<thead class="table-dark">
			<tr>
				<!-- <th class="adjust"></th> -->
				<th>ID</th>
				<th>状態</th>
				<th>種類</th>
				<th>日付</th>
				<th>相手先</th>
				<th>金額</th>
				<th>登録日</th>
				<!-- <th>表示</th> -->
				<th></th>
				<!-- <th></th> -->
				</tr>
			</thead>
			
	<tbody class="body">
	{% for ledger in object_list %}
		<tr>
			<td>{{ ledger.pk }}</td>
			<td>{{ ledger.attachedField }}</td>
			<td>{% if ledger.category == False %} 請求書 {% endif %}{% if ledger.category == True %} 領収書 {% endif %}</td>
			<td>{{ ledger.input_date }}</td>
			<td>{{ ledger.client }}</td>
			<td>{{ ledger.includingTax }}円</td>
			<td>{{ ledger.registration_date }}</td>

		</tr>
	{% endfor%}
	</tbody>
	</table>
</div>

{% endblock%}

D2_app/templates/D2_app/login.html
{% load static%}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="ja">
        <title>Ledger web-system</title>
        <meta name="description" content="ページの概要文を掲載します">
        <meta name="viewport" content="device-width">
        <link rel="stylesheet" href="{% static '/css/login.css'%}">
        <!-- <link rel="stylesheet" href="{%static "/css/password.css" %}"> -->
        <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" 
    </head>

    <body>
        <div id="login">

            <div class="header">
                <div class="back">
                    <img src="{% static "/images/common/LEDGER.png"%}" height="60px" alt="ロゴの名前">
                </div>
                <div class="adjust"></div>
            </div>
            <form name="form-login">
                
                <div class="user-str">
                    ユーザID
                </div>
                <input type="text" id="user" placeholder="UserID">                
                
            <div class="user-str">
                パスワード
            </div>    
              <input type="password" id="pass" placeholder="Password">
              <a href="https://forms.gle/pP7BeJRgqGqNABth9"rel="noopener noreferrer">パスワードを忘れた</a>
            
              <table>
                <tr>
                    <td >
                        <div class="acount">
                            <input type="radio" name="q1" value="一般" style="transform:scale(1.5);"> 一般
                          <input type="radio" name="q1" value="承認者" style="transform:scale(1.5);"> 承認者
                        </div>
                    </td>
                    <td class="l">
                        <div class="login-botton">
                            <input type="submit" value="ログイン" >
                        </div>
                    </td>

                </tr>
                
              </table>
              
                </form>

        </div>
        <div class="signup">
            <a href="{% url 'D2_app:signup' %}" >サインアップはこちらから</a>
        </div>
        <button class="fake" onclick=location.href="{% url 'D2_app:main' %}">fake</button>
 
                
            </body>

    </html>



D2_app/templates/D2_app/main.html
{% extends "base.html" %}
{% load static %}

    {% block css %}<link rel="stylesheet"href="{% static '/css/main.css'%}">{% endblock %}
{% block title %} Add {% endblock %}
{% block page_name %}メイン画面{% endblock %}
{% block main %}
<div class="main" >
    <table class="icons" >
     <tr>
         
         <td class="upload">
             <!-- <div class="tooltip5" style="text-align: center;">     -->
             <div style="text-align: center;">
                <a href="{% url 'D2_app:register' %}">
                 <img src={% static "/images/common/database.png"%}  alt="登録アイコン" >
                 <p class="subtitle" >
                     帳簿の登録
                 </p>
                </a>
             </div>
             <!-- <div class="description5">説明を入力</div>                    -->
             </div>
         </td>
           
         <td class="span"></td>
         <td class="upload">
             <div style="text-align: center;">
                <a href="{% url 'D2_app:ledger_list' %}">
                 <img src={% static "/images/common/admin.png"%}  alt="承認アイコン">
                 <p class="subtitle" >
                     帳簿の承認
                 </p>
                </a>
             </div>                    
         </td>
         <td class="span"></td>
         <td class="upload">
             <div style="text-align: center;">
                <a href="{% url 'D2_app:ledger_list' %}">
                 <img src={% static "/images/common/search.png"%}  alt="検索アイコン">
                 <p class="subtitle" >
                     帳簿の検索
                 </p>
                </a>
             </div>
             
         </td>
     </tr>
    </table>

 </div>
{% endblock %}

D2_app/templates/D2_app/register.html
{% extends "base.html" %}
{% load static %}

{% block title %} Register {% endblock %}
{% block page_name %}register{% endblock %}

{% block main %}
<link href="{% static '/css/register.css'%}" rel="stylesheet">
<form action="{% url 'D2_app:register' %}" method="post">
{% csrf_token %}
{{ form_id }}
<input type="submit"/>
</form>
   <div div id="tbl-bdr">
     <form>
     <table class = "form">
        <tr>
        <th>
        <label>種別</label</th>
        <td>
        <dd><legend>どちらかひとつを選択して下さい</dd>
        <input type="checkbox" value="領収書" id="inq1" checked>
         <label for="inq1">領収書</label>
         <input type="checkbox" value="レシート" id="inq2">
         <label for="inq2">レシート</label></td>
        </tr>
        <tr>
        <th><label>日付</label</th>
        <td><input type="date" placeholder="例）2000-11-11"></td>
        </tr>
        <tr>
        <th><label>相手先</label</th>
        <td><input type="text" placeholder="例）〇〇株式会社"></td>
        </tr>
        <tr>
        <th><label>消費税</label</th>
        <td><input type="integer"></td>
        </tr>
        <tr>
        <th><label>税抜金額</label</th>
        <td><input type="integer"></td>
        </tr>
        <tr>
        <th><label>税込金額</label</th>
        <td><input type="integer"></td>
        </tr>
        <tr>
        <th><label>備考</label</th>
        <td><textarea name="comment"></textarea></td>
        </tr>
     </table>
     </form>
   </div>
   
   <div div id="tbl-bdr">
     <form>
     <table class = "form">
        <tr>
        <td class = "shubetu">種別</td>
        
        <td colspan="2"><dd><legend>どちらかひとつを選択して下さい</dd>{{form.category}}</td>
        </tr>
        <tr>
        <td class = "date">日付</td>
        <td  colspan="2">{{form.input_date}}</td>
        </tr>
        <tr>
        <td class = "client">相手先</td>
        <td colspan="2">{{form.client}}</td>
        </tr>
        <tr>
            <td rowspan="4" class="money">金額</td>   
        </tr>
        <tr>
        <td class = "comsum">消費税</td>
        <td>{{form.consumptionTax}}</td>
        </tr>
        <tr>
        <td class = "exinclude">税抜金額</td>
        <td>{{form.excludingTax}}</td>
        </tr>
        <tr>
        <td class = "include">税込金額</td>
        <td class="A">{{form.includingTax}}</td>
        </tr>
        <tr>
        <td class = "text">備考</td>
        <td colspan="2"><textarea name="comment"></textarea></td>
        </tr>
     </table>
     </form>
   </div>
<ul>
<li><a href="{% url 'D2_app:main' %}"><input type="button" value="登録"></a></li>
<li><a href="{% url 'D2_app:show' %}"><input type="button" value="キャンセル"></a></li>
</ul>
{% endblock %}

D2_app/templates/D2_app/signup.html
{% load static%}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="ja">
        <title>Ledger web-system</title>
        <meta name="description" content="ページの概要文を掲載します">
        <meta name="viewport" content="device-width">
        <!-- <link href="./css/signup.css" rel="stylesheet"> -->
        <link rel="stylesheet" href="{% static "/css/password.css"%}">
        <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" 
    </head>

    <body>
        <div id="login">

            <div class="header">
                <div class="back">
                    <img src="{% static "/images/common/LEDGER.png"%}" height="60px" alt="ロゴの名前">
                </div>
                <div class="adjust"></div>
            </div>
            <form name="form-login">
                
                <div class="user-str">
                    ユーザID(4-7文字)
                </div>
                <input type="text" id="user" required placeholder="UserID" pattern="^[a-zA-Z0-9]+$" maxlength="7" minlength="4">                
                
            <div class="user-str">
                パスワード(8-12文字)
            </div>    
              <input type="password" id="pass" required placeholder="Password" pattern="^[[a-zA-Z0-9]+%+_]+$"maxlength="12" minlength="8">
              <div class="user-str">
                パスワード(確認用)
            </div>    
              <input type="password" id="check-pass" required placeholder="Password" maxlength="12" minlength="8">

              <div class="acount">
                <input type="radio" name="q1" value="一般" style="transform:scale(1.5);"> 一般
                <input type="radio" name="q1" value="承認者" style="transform:scale(1.5);"> 承認者  
              </div>
             
              <div class="user-str">
                メールアドレス
            </div>    
              <input type="email" id="mail"  required placeholder="メールアドレス">

                        <div class="login-botton">
                            <input type="submit" value="登録" >
                        </div>

              
                </form>

        </div>
        <button class="fake" onclick=location.href="{% url 'D2_app:main' %}">fake</button>
 
                
            </body>

    </html>

